### ISSUE TITLE
hardcoded service

### ISSUE THREAD

**Issue by fluidpixel** [ChFlick/firecode#11]
It works for if there is a top level `service cloud.firestore` but not for `service firebase.storage` which has the same basic format.

**Comment by ChFlick** [comment]
Hi @fluidpixel ,
thanks for reporting the issue. 

I think the `service firebase.storage` line is part of the firebase storage rules and not the firestore rules.
The extension was originally built only to support the Firestore rules, and so far I have not really noticed that the rules of the firebase storage are quite equal.

I'm going to add the line, but I'm not sure if every firebase storage rule will be compatible.

**Comment by ChFlick** [comment]
I just released a new version supporting `service firebase.storage` at top level.
