### ISSUE TITLE
functions outside service scope not highlighted

### ISSUE THREAD

**Issue by laurentpayot** [ChFlick/firecode#13]
Thanks for this extension.

I have functions at the top of my rules files (outside `service cloud.firestore { match /databases/{db}/documents {…}` scope) and they are not highlighted.

Cheers,
Laurent

**Comment by ChFlick** [comment]
Thank you very much for reporting the issue @laurentpayot!
I just released a new version containing the fix.

Greetings
Christoph

**Comment by laurentpayot** [comment]
Awesome. The new version is not available yet in VSCode marketplace. How long do you think it will take?

**Comment by ChFlick** [comment]
The extension was somehow not published correctly and the changes did not get in.
I just published it again and just tested it, now it should work :)
