### ISSUE TITLE
Doesn't seem to be matching comments correctly

### ISSUE THREAD

**Issue by otherwiseguy** [ChFlick/firecode#15]
![Screenshot from 2020-07-05 13-27-28](https://user-images.githubusercontent.com/271940/86539595-6c1d9680-bec3-11ea-8200-40c320b0e7d3.png)

**Comment by ChFlick** [comment]
Hi @otherwiseguy,

thanks for reporting the issue.
I think you probably confused [prettier-plugin-firestore-rules](https://github.com/ChFlick/prettier-plugin-firestore-rules) with [firecode](https://github.com/ChFlick/firecode) which is the VS Code extension, as it had exactly these problems :smiley:. The prettier plugin is still WIP and not yet used.

I was actually not aware that you can `allow` without an if-condition, which lead to the weird comment behavior.

The fixed version v1.2.9 was just published and should be available in a few minutes.

Greets
Christoph
