### ISSUE TITLE
Incorrect formatting when using matches function

### ISSUE THREAD

**Issue by awhitford** [ChFlick/firecode#16]
I discovered that formatting is incorrect when using the `matches` function -- it appears to get a little confused with the `match` keyword.

For example:
```
service firebase.storage {
  match /b/{bucket}/o {
    function isSignedIn() {
      return request.auth != null;
    }

    function isWritingImage() {
    return request.resource.contentType.matches('image/.*');
    }
...
  }
}
```

**Comment by ChFlick** [comment]
Hi @awhitford,

thanks for reporting the issues!
I just fixed it and published it with v1.2.10.
