### ISSUE TITLE
Excessive white space at end of a line

### ISSUE THREAD

**Issue by awhitford** [ChFlick/firecode#17]
Is there a way to remove excessive white space at the end of a line?

_(Every time I remove it, the formatting puts it back.)_

**Comment by ChFlick** [comment]
Hi @awhitford,

Could you provide some example rules where that happens?
Thanks!

**Comment by awhitford** [comment]
Sorry I missed this request back in July...  Here is an example:
```
rules_version = '2';
service cloud.firestore {
  match /databases/{database}/documents {
    function isSignedIn() {
      return request.auth != null;
    }
    
    // Collection Group queries...
```
The empty line has spaces.  When I remove them, they are put back.

**Comment by ChFlick** [comment]
Thanks for providing the example, even though some time went by. :smile:

I just fixed it and published a new version where the whitespaces should be gone.

**Comment by awhitford** [comment]
Confirmed that it works great.  Thanks for the fix.
