### ISSUE TITLE
Missing syntax highlighting and formatting for let variables in functions

### ISSUE THREAD

**Issue by 185driver** [ChFlick/firecode#7]
Here's a contrived example that illustrates the issue:
```
function testThis {
  let isSignedIn = request.auth.uid != uid;
  return isSignedIn;
}
```
The `let` variable line syntax isn't highlighted, and it isn't indented properly.

**Comment by ChFlick** [comment]
Thanks again for reporting the issue @185driver.

I just published the new version with the fix to the vs code marketplace.
