### ISSUE TITLE
Missing syntax highlighting and formatting for comments in functions

### ISSUE THREAD

**Issue by 185driver** [ChFlick/firecode#8]
Here's a contrived example that illustrates the issue:
```
function testThis {
  // This is a comment in a function.
  return  request.auth.uid != uid;
}
```
The comment line syntax isn't highlighted correctly, and it isn't indented properly.

**Comment by ChFlick** [comment]
Hi @185driver,

thank you very much for reporting the issue, I just fixed it and I will publish a new version shortly.

**Comment by 185driver** [comment]
Thanks so much. Nice extension!
